baseurl = "https://jentjr.github.io"
languageCode = "en-us"
Title = "jrj"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright notice"
publishDir = "docs"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "jentjr"
  github = "jentjr"
  # Disqus shortname
  disqus = ""
  author = "Justin R. Jent"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Environmental Statistics"
