theme = "basics"
baseURL = "http://jentjr.com/"
languageCode = "en-us"
title = "jrj"

[params]
    author = 'Justin R. Jent'
    github = "jentjr"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
